# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-16 20:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digitalrail', '0002_question_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='additional_prompt',
            field=models.CharField(default='', max_length=500),
            preserve_default=False,
        ),
    ]
