# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-17 15:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digitalrail', '0003_question_additional_prompt'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='rail_id',
            field=models.IntegerField(default=0),
        ),
    ]
