# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-07-16 05:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digitalrail', '0003_imodelquestion_imodel_artifact_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='RailSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timeout_seconds', models.IntegerField(default=180)),
            ],
            options={
                'verbose_name': 'Rail Setting',
                'verbose_name_plural': 'Rail Settings',
            },
        ),
    ]
