# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-07-16 05:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digitalrail', '0004_railsettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='railsettings',
            name='rail_id',
            field=models.IntegerField(default=0),
        ),
    ]
