# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-24 04:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digitalrail', '0004_question_rail_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='related_img_url',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='question',
            name='selected_story_id',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
    ]
