# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-05-24 04:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('digitalrail', '0005_auto_20160524_0403'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='related_img_url',
            new_name='related_img_filename',
        ),
    ]
