# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-07-25 01:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digitalrail', '0005_railsettings_rail_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='imodelquestion',
            name='selected_story_id',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
    ]
