# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-26 04:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digitalrail', '0007_question_case_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='case_number',
            field=models.CharField(default=b'', max_length=25),
        ),
    ]
