# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-11-14 05:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('digitalrail', '0008_auto_20161114_0203'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArtifactDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artifact_heading', models.CharField(blank=True, max_length=500)),
                ('artifact_subheading', models.CharField(blank=True, max_length=500)),
                ('artifact_img_urls', models.CharField(blank=True, max_length=500)),
                ('artifact_rights', models.CharField(blank=True, max_length=500)),
                ('artifact_caption', models.CharField(blank=True, max_length=500)),
                ('artifact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='digitalrail.Artifact')),
            ],
            options={
                'verbose_name': 'Artifact',
                'verbose_name_plural': 'Artifacts',
            },
        ),
    ]
