# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-11-14 05:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('digitalrail', '0009_artifactdetail'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='artifactdetail',
            options={'verbose_name': 'Artifact Detail', 'verbose_name_plural': 'Artifact Detail'},
        ),
    ]
