# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-27 00:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digitalrail', '0009_auto_20160626_0404'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='imodel',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='question',
            name='imodel_question_text',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
