# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-11-14 05:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('digitalrail', '0010_auto_20161114_0520'),
    ]

    operations = [
        migrations.CreateModel(
            name='InteractiveDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interactive_subheading', models.CharField(blank=True, max_length=500)),
                ('interactive_img_url', models.CharField(blank=True, max_length=500)),
                ('artifact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='digitalrail.Artifact')),
            ],
            options={
                'verbose_name': 'Interactive Detail',
                'verbose_name_plural': 'Interactives Detail',
            },
        ),
        migrations.RemoveField(
            model_name='artifactdetail',
            name='artifact_img_urls',
        ),
        migrations.RemoveField(
            model_name='artifactdetail',
            name='artifact_subheading',
        ),
    ]
