# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-11-14 06:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digitalrail', '0011_auto_20161114_0527'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artifact',
            name='has_interactive',
        ),
        migrations.AddField(
            model_name='artifact',
            name='interactive_type',
            field=models.CharField(default='none', max_length=20),
            preserve_default=False,
        ),
    ]
