# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-11-15 05:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digitalrail', '0013_artifactdetail_artifact_faded_text'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artifactdetail',
            name='artifact_faded_text',
        ),
        migrations.AddField(
            model_name='artifact',
            name='artifact_faded_text',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
