# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-11-15 06:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('digitalrail', '0014_auto_20161115_0531'),
    ]

    operations = [
        migrations.RenameField(
            model_name='artifact',
            old_name='artifact_faded_text',
            new_name='artifact_overlay_text',
        ),
    ]
