# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-11-16 16:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('digitalrail', '0015_auto_20161115_0618'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArtifactQA',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artifact_name', models.CharField(blank=True, max_length=500)),
                ('artifact_label', models.CharField(blank=True, max_length=20)),
                ('artifact_dynasty_age', models.CharField(blank=True, max_length=30)),
                ('artifact_questions', models.CharField(blank=True, max_length=500)),
                ('artifact_answers', models.CharField(blank=True, max_length=2000)),
                ('artifact', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='digitalrail.Artifact')),
            ],
            options={
                'verbose_name': 'Artifact Question Answer',
                'verbose_name_plural': 'Artifact Questions Answers',
            },
        ),
    ]
