# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-04-19 06:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digitalrail', '0020_watchinteractivity_selected_story_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='watchinteractivity',
            name='selected_story_id',
            field=models.IntegerField(blank=True, default=-1),
        ),
    ]
