# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-04-19 06:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digitalrail', '0021_auto_20170419_0628'),
    ]

    operations = [
        migrations.AddField(
            model_name='watchinteractivity',
            name='show_story',
            field=models.BooleanField(default=False),
        ),
    ]
