# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-04-22 06:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('digitalrail', '0022_watchinteractivity_show_story'),
    ]

    operations = [
        migrations.CreateModel(
            name='SavedData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('selected_story_id', models.IntegerField(blank=True, default=-1)),
                ('saved_timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Saved Data',
                'verbose_name_plural': 'Saved Data',
            },
        ),
    ]
